### ISSUE TITLE
How to delete the duplicated /templates/index page

### ISSUE THREAD

**Issue by mubiesam** [Pancake-CMS/developer-console#3]
Could not find the way to remove the components from developer-console, 
![127 0 0 1-8081-components-developer-console- -pages-en-us-edit-index-page](https://cloud.githubusercontent.com/assets/11897667/26030830/a82f2f0a-3891-11e7-8a11-8fa1b62a6a60.jpg)

Meanwhile, the concepts is blank...
https://pancake-cms.github.io/#/pages/en-US/pancake-concepts

Thanks

**Comment by prateekjadhwani** [comment]
Yeah, I dont think I have created the delete functionality yet. But for now you can manualy delete them by going to the `/templates/` node in firebase.

Just an FYI. the project is still under development. But contributions are more than welcome :)

Regarding the pancake-concepts page, I havent authored that page yet :(
May be in the coming days (I guess)

**Comment by mubiesam** [comment]
Thanks for your quick response again.

I'm a newbie learning polymer, but like it very much. Will continue to look into pancake-cms, see what i can contribute from the past experience with Drupal.

Feel free to shout if i can be any help...

**Comment by prateekjadhwani** [comment]
Sure, no worries. Even I am a newbie in polymer.  :)
and thanks alot for the kind words.
